// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjlmenoguhcjtoyhfhag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqbG1lbm9ndWhjanRveWhmaGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NjMyMjUsImV4cCI6MjA2ODIzOTIyNX0.ABzPt5KeK7se_UjGeCemY8_n0m2-QtMa9G8_Tyge5wk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});